export const ColorOptions = [
  { value: "#3F7F4E", label: "Army Green" },
  { value: "#333333", label: "Asphalt" },
  { value: "#A1C9F2", label: "Baby Blue" },
  { value: "#000000", label: "Black" },
  { value: "#0000ff", label: "Blue" },
  { value: "#032B44", label: "Blue Navy" },
  { value: "#964B00", label: "Brown" },
  { value: "#4d4d4f", label: "Charcoal" },
  { value: "#FF0033", label: "Cherry Red" },
  { value: "#964B00", label: "Coffee" },
  { value: "#8B0A1A", label: "Cranberry" },
  { value: "#5C5C5C", label: "Deep Heather" },
  { value: "#333333", label: "Dark Grey" },
  { value: "#38373b", label: "Dark Heather" },
  { value: "#03055B", label: "Darkest Blue" },
  { value: "#228B22", label: "Forest Green" },
  { value: "#FFC0CB", label: "Fuschia" },
  { value: "#FFD700", label: "Gold" },
  { value: "#808080", label: "Gray" },
  { value: "#666666", label: "Gravel" },
  { value: "#008000", label: "Green" },
  { value: "#333333", label: "Heather Black" },
  { value: "#87CEEB", label: "Heather Blue" },
  { value: "#C7C5B8", label: "Heather Grey" },
  { value: "#3E8E41", label: "Heather Green" },
  { value: "#3E8E41", label: "Heather Irish Green" },
  { value: "#C51077", label: "Heather Maroon" },
  { value: "#FFD7BE", label: "Heather Peach" },
  { value: "#34C759", label: "Kelly" },
  { value: "#34C759", label: "Kelly Green" },
  { value: "#ADD8E6", label: "Light Blue" },
  { value: "#FFC5C5", label: "Light Pink" },
  { value: "#AFEEEE", label: "Light Turquoise" },
  { value: "#6b2e4d", label: "Maroon" },
  { value: "#6d644b", label: "Military Green" },
  { value: "#5C7135", label: "Moss Green" },
  { value: "#FF69B4", label: "Neon Pink" },
  { value: "#808000", label: "Olive" },
  { value: "#FFA07A", label: "Orange" },
  { value: "#FFC0CB", label: "Pink" },
  { value: "#800080", label: "Purple" },
  { value: "#d2151f", label: "Red" },
  { value: "#4169E1", label: "Royal" },
  { value: "#4169E1", label: "Royal Blue" },
  { value: "#32CD32", label: "Safety Green" },
  { value: "#C0C0C0", label: "Silver" },
  { value: "#708090", label: "Slate" },
  { value: "#8b8b8b", label: "Sport Grey" },
  { value: "#87CEEB", label: "Vintage Heather Blue" },
  { value: "#032B44", label: "Vintage Heather Navy" },
  { value: "#ffffff", label: "White" },
  { value: "#FFFF00", label: "Yellow" },
  { value: "#F4F4F4", label: "Sand" },
  { value: "#B2B2B2", label: "Ash Grey" },
];
